spring:

  application:
    name: migracao_dados_job

  datasource:
    username: username
    password: password
    url: jdbc:mysql://localhost/spring_batch?useSSL=false

  jpa:
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: always

app:

  datasource:
    username: username
    password: password
    url: jdbc:mysql://localhost/migracao_dados?useSSL=false
